### ISSUE TITLE
Question about the article

### ISSUE THREAD

**Issue by avaa999** [Mingrui-Yu/shape_control_DLO_2#1]
Hi, Mingrui! 
   Thank you for providing such a perfect job. While reading your paper, I was confused by formula (12). Why are all rotation-related positions in matrix T multiplied by L? Given that in formula (14) you have normalized the length of each segment of DLO, why not multiply each segment by a different scaling scale ||x_k - x_k-1|| in formula (12)?
    Thank you for your time and help!

**Comment by Mingrui-Yu** [comment]
Thank you for your interest.

The original Jacobian J() depends on the DLO lengths (scale). If we directly use an NN to appoximate J() and generalize to different DLO lengths, we need a large amount of data from DLOs with different lengths, which we were trying to avoid.

As we observe the characteristics shown in Fig. 3, we approximately regard the translation Jacobian is uncorrelated to the DLO lengths, and the rotation Jacobian is proportional to the DLO lengths. Consequently, we separate the J() to two parts in Equation (11). The first part N() is now uncorrelated to the DLO lengths, which will be approximate by an NN. The input of N() is a scale-irrelevant DLO shape representation, which is specified in Equation (14). 

Regarding your question, multiplying the rotation Jacobian Matrix by L is due to the characteristic that rotation Jacobian is approximately proportional to the DLO length L.

**Comment by avaa999** [comment]
Hi, Mingrui!

I appreciate your quick response and the detailed explanation. It solved my issue!
