### ISSUE TITLE
Request for Access to Unity Environment Source Files

### ISSUE THREAD

**Issue by avaa999** [Mingrui-Yu/shape_control_DLO_2#2]
Dear Mingrui,

Thank you for creating such an incredibly meaningful project. As part of my ongoing research, I need to make some modifications to certain components within the environment. Unfortunately, the executable file does not allow for editing or accessing the environment's structure.

Therefore, I would like to kindly ask if it would be possible for you to provide the original Unity project for the environment. Having access to the project files would enable me to make the necessary adjustments while respecting the original framework you have created.

I assure you that any modifications made would be for personal use within my project, and I will give full credit to your work wherever applicable. If there are any terms or conditions regarding the use of the source files, please let me know, and I will be happy to comply.

Thank you for considering my request. I look forward to your response and appreciate your time and assistance.

**Comment by Mingrui-Yu** [comment]
Thank you for your interest. Unfortunately, we do not have any plans to release the source Unity project. The built environment we provided is intended for quick evaluation, not for development.  The simulation of cables in this project is not perfect.

Actually, I almost do not use Unity for robotics anymore due to its inconvenience. There are now several popular robotics simulators starting to support simulation of deformable objects. I highly recommend using [Cable](https://mujoco.readthedocs.io/en/stable/modeling.html#composite-objects) objects in MuJoCo 3, which is modeled by the Discrete Elastic Rod Model.

**Comment by avaa999** [comment]
Thank you for your response. I completely understand your consideration and appreciate your advice. I will have a try. Thank you again for your time and support.
